services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 9090:9090
    environment:
      - APP_DEBUG=true
      - APP_SERVER_HOST=db
      - APP_SERVER_PORT=9090

      - DB_CONNECTION=MYSQL
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=toor
      - DB_NAME=tender-app
  
  db:
    image: bitnami/mysql
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=tender-app
      - MYSQL_ROOT_PASSWORD=toor
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-ptoor", "-e", "show schemas"]
      timeout: 10s